profile: dev
mode: history # 程序模式 daily/history

cron: 0 0 1 1 * ?
historyStart: 2014-01-01
historyEnd: 2022-09-14
log:
  path: ./logs/log

db:
  host: 10.72.234.78
  port: 1521
  serviceName: ORCL
  username: YTHZNJCPT
  password: HongYou20181221
  maxOpenConns: 10
  dataTable: DBA01
  wellTable: V_CD_WELL_SOURCE

# taos
td:
  host: 10.72.234.78
  port: 6030
  #  port: 6041
  user: root
  password: taosdata
  maxOpenConns: 10
  dataBase: qx
  sTable: dba01

