# 程序模式 dev/prod
#profile: prod

cron: 0 0 1 1 * ?
historyStart: 2014-11-05
historyEnd: 2023-03-26

db:
  host: 10.72.234.78
  port: 1521
  serviceName: ORCL
  username: YTHZNJCPT
  password: HongYou20181221
  dataTable: DBA01_TEST
  wellTable: V_CD_WELL_SOURCE_TEST

# taos
td:
  host: 10.72.234.78
  port: 6041
  user: root
  password: taosdata
  maxOpenConns: 20
  dataBase: qx
  sTable: dba01

